spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url:  jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 1111
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
